### ISSUE TITLE
Menus disappear on mouseout

### ISSUE THREAD

**Issue by jmartsch** [lossendae/trendy#1]
I really love your theme but there is one big problem (tested in IE 9.0 and Chrome 16):
When i move my mouse on a top menu item and then want to go the submenu the submenu just disappears. 
Sometimes it works normally, but seldom.

Here is a screencast i made: http://screencast-o-matic.com/watch/clVlXBxIU

When you fix it, it´s the best theme for modx manager :)

**Comment by lossendae** [comment]
I'll look into it for next release
